// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddHost(arg1:string,arg2:string):Promise<number>;

export function GetHosts():Promise<Array<main.HostEntry>>;

export function LoadConfig():Promise<void>;

export function RemoveHost(arg1:number):Promise<void>;

export function SaveConfig():Promise<void>;
