// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHost(arg1, arg2) {
  return window['go']['main']['App']['AddHost'](arg1, arg2);
}

export function GetHosts() {
  return window['go']['main']['App']['GetHosts']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function RemoveHost(arg1) {
  return window['go']['main']['App']['RemoveHost'](arg1);
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}
